name: merge-gate

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: medamb/logging_framework:latest
      volumes:
        - ${{github.workspace}}:${{github.workspace}}

    steps:
    - uses: actions/checkout@v3

    - name: format-check
      run: ${{github.workspace}}/scripts/format-checker.sh

    - name: lint-check
      run: ${{github.workspace}}/scripts/lint-checker.sh

    - name: build
      run: cmake -B ${{github.workspace}}/build && cmake --build ${{github.workspace}}/build

    - name: test
      working-directory: ${{github.workspace}}
      run: ls

